### ISSUE TITLE
.NET 7 doesn`t create blizzless.exe

### ISSUE THREAD

**Issue by Oduvan4** [Forkas/blizzless-diiis#4]
I did everything according to the instructions, but the compilation d`t working, .NET 7 is installed, bin folder is empty

**Comment by Forkas** [comment]
How do you compile a project? What's wrong with you?

**Comment by danthespal** [comment]
yes, the project cannot be compiled, there is an error

"Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name '_dbQuests' does not exist in the current context	Blizzless	C:\TOOLS\D3Server\forkas\blizzless-diiis\src\DiIiS-NA\BGS-Server\Toons\Toon.cs	897	Active
"

**Comment by Forkas** [comment]
Download the latest version of NET 7.0 and compile via the NET 7.0 console.
